QUESTIONS = (
    #General Questions
    "Kako se zoveš i odakle dolaziš?",
    "Šta te motivisalo da učiš srpski jezik?",
    "Koje su tvoje omiljene knjige?",
    "Šta voliš da radiš u slobodno vreme?",
    "Koji je tvoj omiljeni film i zašto?",
    "Koji je tvoj omiljeni muzički izvođač?",
    "Da li voliš da putuješ? Ako da, gde si sve bio/la?",
    "Šta je najlepše mesto koje si posetio/la?",
    "Koji je tvoj omiljeni recept?",
    "Da li voliš sport? Koji sport pratiš ili igraš?",
    #Food and Drink
    "Koje je tvoje omiljeno jelo?",
    "Da li znaš da kuvaš? Koje jelo ti najbolje ide?",
    "Koji je tvoj omiljeni restoran u tvom gradu?",
    "Šta misliš o tradicionalnoj srpskoj hrani?",
    "Da li si ikada probao/la nešto novo i neobično?",
    "Koji je tvoj omiljeni desert?",
    "Da li piješ kafu? Kako je piješ?",
    "Da li voliš vino? Koji je tvoj omiljeni tip vina?",
    "Da li si ikada pravio/la domaće rakije?",
    "Koji su tvoji omiljeni brzi obroci?",
    #Culture and Traditions
    "Koji je tvoj omiljeni srpski praznik?",
    "Šta ti se najviše sviđa u srpskoj kulturi?",
    "Da li znaš neki srpski narodni običaj?",
    "Koji je tvoj omiljeni deo srpske istorije?",
    "Da li si ikada bio/la na srpskim tradicionalnim manifestacijama?",
    "Kako proslavljaš Božić ili Novu godinu?",
    "Koji je tvoj omiljeni srpski pesnik ili književnik?",
    "Da li pratiš srpske filmove? Koji ti je najdraži?",
    "Koji je tvoj omiljeni srpski muzički stil?",
    "Da li znaš neku srpsku narodnu pesmu?",
    #Travel
    "Koje države si posetio/la?",
    "Koje mesto ti je najlepše bilo za vreme putovanja?",
    "Da li imaš planove za sledeće putovanje?",
    "Šta je najzanimljivije što si video/la tokom putovanja?",
    "Da li preferiraš more ili planine za odmor?",
    "Koje je tvoje omiljeno odredište za vikend izlete?",
    "Koje destinacije su ti na listi želja?",
    "Da li si ikada putovao/la samostalno?",
    "Koje je najneobičnije mesto koje si posetio/la?",
    "Koji je najlepši grad u kojem si bio/la?",
    #Personal Experience
    "Koji je najvažniji životni trenutak za tebe?",
    "Da li imaš neki hobi koji te posebno ispunjava?",
    "Kako provodiš svoj slobodan dan?",
    "Da li imaš neke životne ciljeve koje želiš da postigneš?",
    "Šta te najviše inspiriše u životu?",
    "Kako se nosiš sa stresom?",
    "Koji je najvažniji savet koji si ikada dobio/la?",
    "Da li imaš omiljeni citat ili izreku?",
    "Kako se osećaš kada postigneš neki cilj?",
    "Koji je tvoj najveći izazov koji si prevazišao/la?",
    #Family and Friends
    "Kakav je tvoj odnos sa porodicom?",
    "Da li imaš braću ili sestre?",
    "Koji je tvoj najlepši trenutak s porodicom?",
    "Kako provodiš vreme sa prijateljima?",
    "Da li imaš nekog posebnog prijatelja?",
    "Kako se upoznala/la sa svojim najboljim prijateljem/prijateljicom?",
    "Koji je najlepši poklon koji si ikada dobio/la od prijatelja?",
    "Kako održavaš odnose sa prijateljima koji žive daleko?",
    "Da li se često viđaš sa porodicom?",
    "Kako je izgledala tvoja porodična proslava?",
    #Work and Study
    "Šta te najviše privuklo tvojoj trenutnoj profesiji?",
    "Koji je tvoj najvažniji profesionalni cilj?",
    "Da li voliš svoj posao?",
    "Kako se nosiš sa radnim stresom?",
    "Koje veštine smatraš najvažnijim za svoj posao?",
    "Da li planiraš da menjaš karijeru?",
    "Koje su tvoje omiljene teme za istraživanje ili učenje?",
    "Da li si ikada učio/la neki drugi jezik?",
    "Koji je najvažniji lekcija koju si naučio/la na poslu?",
    "Da li imaš mentor ili uzor u svom poslu?",
    #Technology and Media
    "Koji je tvoj omiljeni tehnološki uređaj?",
    "Da li pratiš tehnološke novitete?",
    "Koji je tvoj omiljeni društveni medij?",
    "Da li imaš blog ili kanal na YouTube-u?",
    "Koji je najkorisniji aplikacija koju koristiš?",
    "Da li voliš da pratiš vesti online?",
    "Kako provodiš vreme na internetu?",
    "Da li koristiš pametan telefon? Koji?",
    "Koji je tvoj omiljeni online servis za streaming?",
    "Kako tehnologija menja tvoje svakodnevne navike?",
    #Hobbies and Interests
    "Da li imaš neki umetnički hobi?",
    "Šta te najviše interesuje u slobodno vreme?",
    "Da li voliš da se baviš sportom?",
    "Koji je tvoj omiljeni način opuštanja?",
    "Da li imaš neki kolekcionarski hobi?",
    "Kako se baviš svojim hobijem?",
    "Da li si ikada učestvovao/la u nekoj umetničkoj predstavi ili izložbi?",
    "Koje knjige najviše voliš da čitaš?",
    "Da li ti je važno da razvijaš svoje hobije?",
    "Koji je najzanimljiviji hobi koji si probao/la?",
    #Society and Culture
    "Šta misliš o trenutnim društvenim promenama?",
    "Koje društvene teme te najviše interesuju?",
    "Kako se tvoje mišljenje menja u vezi sa određenim društvenim pitanjima?",
    "Koji je tvoj stav o ekologiji i zaštiti životne sredine?",
    "Da li se baviš volontarizmom? Kako?",
    "Šta misliš o kulturnoj raznolikosti u tvom gradu?",
    "Kako društvo utiče na tvoje odluke?",
    "Da li pratiš političke događaje? Zašto?",
    "Koji su tvoji stavovi o obrazovnom sistemu u tvojoj zemlji?",
    "Kako bi poboljšao/la svoj grad ili zajednicu?",
    #Relationships and Emotions
    "Kako izražavaš svoja osećanja?",
    "Šta misliš o važnosti komunikacije u vezi?",
    "Kako održavaš dobre odnose sa partnerom?",
    "Da li veruješ u ljubav na prvi pogled?",
    "Kako se nosiš sa konfliktima u vezi?",
    "Šta te najviše privlači kod drugih ljudi?",
    "Da li si ikada imao/la teške emotivne trenutke? Kako si ih prevazišao/la?",
    "Koja je najvažnija osobina koju tražiš kod partnera?",
    "Kako se osećaš kada treba da doneseš teške odluke?",
    "Da li misliš da je važno da se u vezi razvija zajedno sa partnerom?",
    #Future Plans
    "Koji su tvoji ciljevi za sledećih pet godina?",
    "Da li planiraš da se preseliš u drugi grad ili državu?",
    "Šta bi voleo/la da postigneš u svojoj karijeri?",
    "Da li planiraš da započneš neki novi projekat ili hobi?",
    "Koje su tvoje dugoročne životne ambicije?",
    "Da li imaš planove za obrazovanje ili dodatnu obuku?",
    "Kako vidiš sebe za deset godina?",
    "Da li planiraš da se upustiš u neki novi izazov?",
    "Šta bi voleo/la da menjaš u svom životu u budućnosti?",
    "Koje su tvoje nade za budućnost tvoje zajednice ili društva?",
    #Language and Learning
    "Šta vas je motivisalo da učite srpski jezik i šta vas i dalje motiviše?",
    "Kako si naučio/la srpski jezik?",
    "Da li imaš neki savet za učenje jezika?",
    "Koje je najteže pravilo koje si naučio/la u srpskom jeziku?",
    "Koji su najveći izazovi koje ste naišli tokom učenja srpskog jezika?",
    "Da li si nekada naručivao/la nešto telefonom na srpskom?",
    "Kako redovno vežbate govor na srpskom jeziku?",
    "Koji resursi (knjige, aplikacije, sajtovi) su vam najviše pomogli u procesu učenja?",
    "Koje knjige ili filmove na srpskom jeziku preporučujete za učenje jezika?",
    "Da li upotrebljavate društvene mreže i online zajednice za vežbanje srpskog jezika?",
    "Kako procenjujete svoj napredak u učenju srpskog jezika?",
    "Da li imate neku omiljenu frazu ili izreku na srpskom jeziku?",
    "Koje veštine (govor, slušanje, čitanje, pisanje) vam najteže idu i zašto?",
)